[workspace]

resolver = "2"

members = [ 
  "array", "bit", "bits", "bsearch", "dp", "graph", "hashing", "math", "pfx", "pq", "recursion", "simulation", "slidingwindow", "sorting", "stack", "string",
]
